import React from 'react';
import Head from 'next/head'
import FolderTree from '@/components/FolderTree';
import { Inter } from 'next/font/google';
import type { TreeNode } from '@/types/TreeNode';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['vietnamese'] })

const folders: TreeNode[] = [
    {
        __typename: 'TreeNode',
        value: 'Folder 1',
        children: [
            {
                __typename: 'TreeNode',
                value: 'Folder 1.1',
                children: [
                    {
                        __typename: 'TreeNode',
                        value: 'Folder 1.1.1',
                        children: [
                            {
                                __typename: 'TreeNode',
                                value: 'Screenshot1.png',
                                children: []
                            },
                            {
                                __typename: 'TreeNode',
                                value: 'Screenshot2.png',
                                children: []
                            },
                            {
                                __typename: 'TreeNode',
                                value: 'Screenshot3.png',
                                children: []
                            },
                            {
                                __typename: 'TreeNode',
                                value: 'Screenshot4.png',
                                children: []
                            },
                        ]
                    },
                    {
                        __typename: 'TreeNode',
                        value: 'Folder 1.1.2',
                        children: [
                            {
                                __typename: 'TreeNode',
                                value: 'documentSheet.xlsx',
                                children: []
                            },
                            {
                                __typename: 'TreeNode',
                                value: 'doc.txt',
                                children: []
                            },
                            {
                                __typename: 'TreeNode',
                                value: 'banner.png',
                                children: []
                            },
                            {
                                __typename: 'TreeNode',
                                value: 'cover.jpeg',
                                children: []
                            },
                        ]
                    }
                ]
            }
        ]
    }
];

const Home = () => {
    return (
        <>
            <Head>
                <title>POC - Folder Node Tree Structure</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                {/* <h2 className={inter.className}>
                    Learn <span>-&gt;</span>
                </h2> */}
                    <p>
                        <span className={inter.className}>
                            Folder Node Tree Structure
                        </span><br/>
                        <code className={styles.code}>--- with Breadcrumb Navigation Flow ---</code>
                    </p>
                </div>
                <div className={styles.description}>
                    <FolderTree folders={folders} />
                </div>
            </main>
        </>
    );
};

export default Home;
